#!/bin/sh
#
# Run access-control-proxy
#

cd /usr/local/bin/access-control-proxy/
NODE_ENV=production npm start &
echo $! > /tmp/ac-proxy.pid

PIDFILE=/tmp/ac-proxy.pid
PID=`cat $PIDFILE`

while [ -e /proc/$PID ]
do
	sleep 1
done
